//! System notifications (I-135) through macOS's UNUserNotificationCenter.
//!
//! Not `tauri-plugin-notification`: on macOS its permission calls always answer "granted" and it
//! has no click callback, so "open the chat you clicked" and "notifications are turned off in
//! System Settings" couldn't work.
//!
//! - Commands (main window only; permissions generated by build.rs):
//!   - `notify_permission`: "granted" | "denied" | "default" | "unavailable"
//!   - `notify_request`: shows the system prompt the first time
//!   - `notify_show`: `{ id, title, subtitle?, body, data }`
//!   - `notify_ready`: the page listens for clicks now
//!   The web side is packages/app-core/src/lib/desktop.ts + lib/system-notifications.ts.
//! - A banner with the same `id` replaces the earlier one. `data` (the chat to open, JSON) travels
//!   in the notification's userInfo, so a click still routes after a relaunch.
//! - Clicking a banner focuses the window and emits `glade:notification-click` with `data`. A click
//!   that arrives before the page is listening (it launched the app) is kept and handed over by
//!   `notify_ready`. The delegate is installed once in `setup`, before launching finishes.
//! - Banners also show while Glade is in front (`willPresentNotification`); the web app decides
//!   whether to post one at all (its "Only while Glade is in the background" setting).
//! - UNUserNotificationCenter needs a real app bundle with a bundle id: a bare binary (e.g.
//!   `cargo build` output run directly) gets "unavailable" and no banners, never a crash. It works
//!   in ad-hoc signed bundles (what `pnpm tauri:install` makes); the first request shows the
//!   system prompt for "Glade" and the choice then lives in System Settings › Notifications.

use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Mutex, OnceLock};

use tauri::{AppHandle, Emitter};

pub const CLICK_EVENT: &str = "glade:notification-click";

static APP: OnceLock<AppHandle> = OnceLock::new();
/// The page called `notify_ready` (it has a click listener).
static READY: AtomicBool = AtomicBool::new(false);
/// A click that came before the page was ready.
static PENDING_CLICK: Mutex<Option<String>> = Mutex::new(None);

/// Longest accepted texts (banners show a few lines anyway).
const MAX_TEXT: usize = 1000;
const MAX_DATA: usize = 4096;

/// Install the click delegate. Call once from `setup`.
pub fn install(app: &AppHandle) {
    let _ = APP.set(app.clone());
    #[cfg(target_os = "macos")]
    macos::install_delegate();
}

/// A banner was clicked (main thread).
#[allow(dead_code)] // only called on macOS
fn clicked(data: String) {
    let Some(app) = APP.get() else { return };
    crate::focus_main(app);
    if READY.load(Ordering::SeqCst) {
        let _ = app.emit(CLICK_EVENT, data);
    } else {
        *PENDING_CLICK.lock().unwrap() = Some(data);
    }
}

fn clip(text: &str, max: usize) -> String {
    if text.len() <= max {
        return text.to_string();
    }
    let mut end = max;
    while !text.is_char_boundary(end) {
        end -= 1;
    }
    text[..end].to_string()
}

#[tauri::command]
pub async fn notify_permission() -> String {
    run_blocking(|| permission()).await
}

#[tauri::command]
pub async fn notify_request() -> String {
    run_blocking(|| request()).await
}

#[tauri::command]
pub fn notify_show(id: String, title: String, subtitle: Option<String>, body: String, data: String) -> Result<(), String> {
    if id.is_empty() || id.len() > 500 || data.len() > MAX_DATA {
        return Err("invalid notification".into());
    }
    show(&clip(&id, 500), &clip(&title, MAX_TEXT), subtitle.as_deref().map(|s| clip(s, MAX_TEXT)).as_deref(), &clip(&body, MAX_TEXT), &data)
}

#[tauri::command]
pub fn notify_ready() -> Option<String> {
    READY.store(true, Ordering::SeqCst);
    PENDING_CLICK.lock().unwrap().take()
}

async fn run_blocking(f: fn() -> &'static str) -> String {
    tauri::async_runtime::spawn_blocking(f).await.unwrap_or("unavailable").to_string()
}

#[cfg(not(target_os = "macos"))]
fn permission() -> &'static str {
    "unavailable"
}
#[cfg(not(target_os = "macos"))]
fn request() -> &'static str {
    "unavailable"
}
#[cfg(not(target_os = "macos"))]
fn show(_id: &str, _title: &str, _subtitle: Option<&str>, _body: &str, _data: &str) -> Result<(), String> {
    Err("notifications are only available on macOS".into())
}

#[cfg(target_os = "macos")]
use macos::{permission, request, show};

#[cfg(target_os = "macos")]
mod macos {
    use std::sync::mpsc;
    use std::time::Duration;

    use block2::RcBlock;
    use objc2::rc::Retained;
    use objc2::runtime::{AnyObject, Bool, NSObject, NSObjectProtocol, ProtocolObject};
    use objc2::{define_class, msg_send, AllocAnyThread};
    use objc2_foundation::{NSBundle, NSDictionary, NSError, NSString};
    use objc2_user_notifications::{
        UNAuthorizationOptions, UNAuthorizationStatus, UNMutableNotificationContent, UNNotification,
        UNNotificationPresentationOptions, UNNotificationRequest, UNNotificationResponse, UNNotificationSettings,
        UNNotificationSound, UNUserNotificationCenter, UNUserNotificationCenterDelegate,
    };

    /// userInfo key carrying the web app's `data`.
    const DATA_KEY: &str = "glade";
    const WAIT: Duration = Duration::from_secs(120);

    /// The notification center, or `None` without an app bundle (it would raise an exception).
    fn center() -> Option<Retained<UNUserNotificationCenter>> {
        let bundle = NSBundle::mainBundle();
        bundle.bundleIdentifier()?;
        if !bundle.bundlePath().to_string().ends_with(".app") {
            return None;
        }
        objc2::exception::catch(|| UNUserNotificationCenter::currentNotificationCenter()).ok()
    }

    fn status_name(status: UNAuthorizationStatus) -> &'static str {
        match status {
            UNAuthorizationStatus::NotDetermined => "default",
            UNAuthorizationStatus::Denied => "denied",
            _ => "granted", // authorized, provisional, ephemeral
        }
    }

    pub fn permission() -> &'static str {
        let Some(center) = center() else { return "unavailable" };
        let (tx, rx) = mpsc::channel();
        let block = RcBlock::new(move |settings: std::ptr::NonNull<UNNotificationSettings>| {
            let status = unsafe { settings.as_ref() }.authorizationStatus();
            let _ = tx.send(status_name(status));
        });
        center.getNotificationSettingsWithCompletionHandler(&block);
        rx.recv_timeout(Duration::from_secs(5)).unwrap_or("unavailable")
    }

    pub fn request() -> &'static str {
        let Some(center) = center() else { return "unavailable" };
        let (tx, rx) = mpsc::channel();
        let block = RcBlock::new(move |_granted: Bool, _error: *mut NSError| {
            let _ = tx.send(());
        });
        center.requestAuthorizationWithOptions_completionHandler(UNAuthorizationOptions::Alert | UNAuthorizationOptions::Sound, &block);
        // The prompt waits for the user; the answer is read back from the settings.
        let _ = rx.recv_timeout(WAIT);
        permission()
    }

    pub fn show(id: &str, title: &str, subtitle: Option<&str>, body: &str, data: &str) -> Result<(), String> {
        let center = center().ok_or("notifications are unavailable")?;
        let content = UNMutableNotificationContent::new();
        content.setTitle(&NSString::from_str(title));
        if let Some(subtitle) = subtitle {
            content.setSubtitle(&NSString::from_str(subtitle));
        }
        content.setBody(&NSString::from_str(body));
        content.setSound(Some(&UNNotificationSound::defaultSound()));
        let key = NSString::from_str(DATA_KEY);
        let value = NSString::from_str(data);
        let info = NSDictionary::<NSString, NSString>::from_slices(&[&*key], &[&*value]);
        // SAFETY: a dictionary of strings is a valid property-list userInfo.
        unsafe { content.setUserInfo(Retained::cast_unchecked::<NSDictionary>(info).as_ref()) };
        let request = UNNotificationRequest::requestWithIdentifier_content_trigger(&NSString::from_str(id), &content, None);
        center.addNotificationRequest_withCompletionHandler(&request, None);
        Ok(())
    }

    fn data_of(response: &UNNotificationResponse) -> Option<String> {
        let info = response.notification().request().content().userInfo();
        let key = NSString::from_str(DATA_KEY);
        let value: Option<Retained<AnyObject>> = unsafe { msg_send![&*info, objectForKey: &*key] };
        value?.downcast::<NSString>().ok().map(|s| s.to_string())
    }

    define_class!(
        #[unsafe(super(NSObject))]
        #[name = "GladeNotificationDelegate"]
        struct Delegate;

        unsafe impl NSObjectProtocol for Delegate {}

        unsafe impl UNUserNotificationCenterDelegate for Delegate {
            #[unsafe(method(userNotificationCenter:willPresentNotification:withCompletionHandler:))]
            fn will_present(
                &self,
                _center: &UNUserNotificationCenter,
                _notification: &UNNotification,
                handler: &block2::DynBlock<dyn Fn(UNNotificationPresentationOptions)>,
            ) {
                handler.call((UNNotificationPresentationOptions::Banner
                    | UNNotificationPresentationOptions::List
                    | UNNotificationPresentationOptions::Sound,));
            }

            #[unsafe(method(userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:))]
            fn did_receive(&self, _center: &UNUserNotificationCenter, response: &UNNotificationResponse, handler: &block2::DynBlock<dyn Fn()>) {
                if let Some(data) = data_of(response) {
                    super::clicked(data);
                }
                handler.call(());
            }
        }
    );

    impl Delegate {
        fn new() -> Retained<Self> {
            let this = Self::alloc().set_ivars(());
            unsafe { msg_send![super(this), init] }
        }
    }

    pub fn install_delegate() {
        let Some(center) = center() else {
            eprintln!("[glade] notifications unavailable (no app bundle)");
            return;
        };
        let delegate = Delegate::new();
        center.setDelegate(Some(ProtocolObject::from_ref(&*delegate)));
        // The center holds its delegate weakly: keep ours for the app's lifetime.
        std::mem::forget(delegate);
    }
}
