/**
 * A custom command for Claude Code (I-201) as a single executable: the Agent SDK takes one path
 * (`pathToClaudeCodeExecutable`) and appends its own arguments, so `mywrapper claude --add-dir x`
 * becomes a tiny generated script that execs the wrapper with the user's leading arguments:
 *
 *   #!/bin/sh
 *   exec '/usr/local/bin/mywrapper' 'claude' '--add-dir' 'x' "$@"
 *
 *   claudeShim("/usr/local/bin/mywrapper", ["claude"])   // "/tmp/…/glade-claude-shims/claude-1a2b…"
 *
 * One file per command (named by its content's hash), in a temp folder, written atomically and
 * again whenever it's missing (temp folders get cleaned). No file extension: the SDK runs
 * `.js`/`.ts` paths with node, anything else directly. stdin/stdout pass through untouched (`exec`).
 */
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, renameSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/** Default folder for the scripts. */
export function defaultShimDir(): string {
  return join(tmpdir(), "glade-claude-shims");
}

const quote = (word: string) => `'${word.replace(/'/g, `'\\''`)}'`;

/** The script's text for `program` (an absolute path) and its leading `args`. */
export function claudeShimScript(program: string, args: readonly string[]): string {
  return `#!/bin/sh\n# Generated by Glade (custom Claude Code command). Safe to delete.\nexec ${[program, ...args].map(quote).join(" ")} "$@"\n`;
}

/** Path of an executable script running `program args… "$@"` (written when missing). */
export function claudeShim(program: string, args: readonly string[], dir = defaultShimDir()): string {
  const script = claudeShimScript(program, args);
  const path = join(dir, `claude-${createHash("sha256").update(script).digest("hex").slice(0, 16)}`);
  if (existsSync(path)) return path;
  mkdirSync(dir, { recursive: true });
  const tmp = `${path}.${process.pid}.${Date.now()}.tmp`;
  writeFileSync(tmp, script, { mode: 0o755 });
  renameSync(tmp, path);
  return path;
}
